// Generated by CoffeeScript 1.10.0
var AccessDenied, PageNotFound, React, Unauthorized;

React = require('react');

Unauthorized = function() {
  return React.createElement("div", null, "Not Authorized");
};

AccessDenied = function() {
  return React.createElement("div", null, "Access Denied");
};

PageNotFound = function() {
  return React.createElement("div", null, "Page Not Found");
};

module.exports = {
  Unauthorized: Unauthorized,
  AccessDenied: AccessDenied,
  PageNotFound: PageNotFound
};
