// Generated by CoffeeScript 1.10.0
var App, React,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

React = require('react');

App = (function(superClass) {
  extend(App, superClass);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.propTypes = {
    className: React.PropTypes.string,
    router: React.PropTypes.object.isRequired,
    onLogoutRequest: React.PropTypes.func
  };

  App.prototype.render = function() {
    return React.createElement("div", {
      "className": this.props.className || 'app'
    }, React.createElement("button", {
      "onClick": this.props.router.goBack.bind(this.props.router)
    }, "Back"), React.createElement("hr", null), this.props.router.createTargetElement(), React.createElement("hr", null), (this.props.onLoginRequest ? React.createElement("p", null, React.createElement("button", {
      "onClick": this.props.onLoginRequest
    }, "Login")) : this.props.onLogoutRequest ? React.createElement("p", null, React.createElement("button", {
      "onClick": this.props.onLogoutRequest
    }, "Logout")) : void 0));
  };

  return App;

})(React.Component);

module.exports = App;
