// Generated by CoffeeScript 1.10.0
var MockContentStore;

MockContentStore = (function() {
  function MockContentStore() {
    this._currentTarget = null;
    this._locationTargets = {};
  }

  MockContentStore.prototype.setCurrentTargetInTest = function(target) {
    return this._currentTarget = target;
  };

  MockContentStore.prototype.getCurrentTarget = function() {
    return this._currentTarget;
  };

  MockContentStore.prototype.setLocationTargetInTest = function(location, target) {
    return this._locationTargets[(location != null ? location.pathname : void 0) || '/'] = target;
  };

  MockContentStore.prototype.getLocationTarget = function(location) {
    return this._locationTargets[(location != null ? location.pathname : void 0) || '/'];
  };

  return MockContentStore;

})();

module.exports = MockContentStore;
