// Generated by CoffeeScript 1.10.0
var ContentStore, EventEmitter, RouteTargetResolver, StatusCodes,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

EventEmitter = require('events').EventEmitter;

RouteTargetResolver = require('../route-target-resolver');

StatusCodes = require('../status-codes');

ContentStore = (function(superClass) {
  extend(ContentStore, superClass);

  function ContentStore(arg) {
    var dispatcher;
    dispatcher = arg.dispatcher;
    this._handleTargetActivate = bind(this._handleTargetActivate, this);
    this._handleTargetAdd = bind(this._handleTargetAdd, this);
    this._dispatcher = dispatcher;

    /**
     * @type {!Object.<
     *   (string|StatusCodes),
     *   (string|StatusCodes|ReactElement|
     *     function(Object.<string, string>):(string|StatusCodes|ReactElement))
     * >}
     */
    this._targets = {};

    /** @type {!Object.<string, string|number>} */
    this._currentTargetParams = {};

    /** @type {string|StatusCodes|null} */
    this._currentTargetPath = null;

    /** @type {string|StatusCodes|ReactElement} */
    this._currentTargetElement = null;
  }

  ContentStore.prototype.init = function() {
    this._dispatcher.on('target-add', this._handleTargetAdd);
    return this._dispatcher.on('target-activate', this._handleTargetActivate);
  };

  ContentStore.prototype.getCurrentTarget = function() {
    return {
      targetPath: this._currentTargetPath,
      params: this._currentTargetParams
    };
  };

  ContentStore.prototype.getTargetElement = function(targetPath, params) {
    var resolver;
    resolver = new RouteTargetResolver(this._targets);
    return resolver.resolveTarget(targetPath, params);
  };

  ContentStore.prototype.getCurrentTargetElement = function() {
    return this._currentTargetElement;
  };

  ContentStore.prototype._handleTargetAdd = function(arg) {
    var content, targetKey;
    targetKey = arg.targetKey, content = arg.content;
    this._targets[targetKey] = content || null;
    this._updateCurrentTargetElement();
    return this.emit('change');
  };

  ContentStore.prototype._handleTargetActivate = function(arg) {
    var params, targetPath;
    targetPath = arg.targetPath, params = arg.params;
    this._currentTargetPath = targetPath;
    this._currentTargetParams = params;
    this._updateCurrentTargetElement();
    return this.emit('change');
  };

  ContentStore.prototype._updateCurrentTargetElement = function() {
    if (this._currentTargetPath) {
      return this._currentTargetElement = this.getTargetElement(this._currentTargetPath, this._currentTargetParams);
    } else {
      return this._currentTargetElement = this.getTargetElement(StatusCodes.NOT_FOUND);
    }
  };

  return ContentStore;

})(EventEmitter);

module.exports = ContentStore;
