// Generated by CoffeeScript 1.10.0
var MockLocationStore;

MockLocationStore = (function() {
  function MockLocationStore() {
    this._locationBase = null;
    this._currentLocation = null;
    this._effectiveLocation = null;
  }

  MockLocationStore.prototype.setLocationBaseInTest = function(locationBase) {
    return this._locationBase = locationBase || null;
  };

  MockLocationStore.prototype.getLocationBase = function() {
    return this._locationBase;
  };

  MockLocationStore.prototype.setCurrentLocationInTest = function(location) {
    return this._currentLocation = location;
  };

  MockLocationStore.prototype.getCurrentLocation = function() {
    return this._currentLocation;
  };

  MockLocationStore.prototype.setEffectiveLocationInTest = function(location) {
    return this._effectiveLocation = location;
  };

  MockLocationStore.prototype.getEffectiveLocation = function() {
    return this._effectiveLocation;
  };

  return MockLocationStore;

})();

module.exports = MockLocationStore;
