// Generated by CoffeeScript 1.10.0
var MockRouteStore;

MockRouteStore = (function() {
  function MockRouteStore() {
    this._locationTargets = {};
  }

  MockRouteStore.prototype.setLocationTargetInTest = function(location, target) {
    return this._locationTargets[(location != null ? location.pathname : void 0) || '/'] = target;
  };

  MockRouteStore.prototype.getLocationTarget = function(location) {
    return this._locationTargets[(location != null ? location.pathname : void 0) || '/'];
  };

  return MockRouteStore;

})();

module.exports = MockRouteStore;
