// Generated by CoffeeScript 1.10.0
var ContentStore, EventEmitter, LocationStore, RouteTargetResolver, Router, StatusCodes, Target, createRouter, history;

history = require('history');

ContentStore = require('./stores/content-store');

EventEmitter = require('events').EventEmitter;

LocationStore = require('./stores/location-store');

Router = require('./router');

RouteTargetResolver = require('./route-target-resolver');

StatusCodes = require('./status-codes');

Target = require('./components/target');

createRouter = function(arg) {
  var contentStore, dispatcher, historyDriver, historyManager, locationBase, locationStore, ref, router;
  ref = arg != null ? arg : {}, historyDriver = ref.historyDriver, locationBase = ref.locationBase;
  historyManager = (function() {
    switch (historyDriver) {
      case 'memory':
        return history.useQueries(history.createMemoryHistory)();
      default:
        return history.useQueries(history.createHistory)();
    }
  })();
  dispatcher = new EventEmitter();
  contentStore = new ContentStore({
    dispatcher: dispatcher
  });
  locationStore = new LocationStore({
    dispatcher: dispatcher
  });
  router = new Router({
    dispatcher: dispatcher,
    contentStore: contentStore,
    historyManager: historyManager,
    locationStore: locationStore
  });
  contentStore.init();
  locationStore.init();
  if (locationBase) {
    router.setLocationBase(locationBase);
  }
  router.init();
  return router;
};

module.exports = {
  StatusCodes: StatusCodes,
  ContentStore: ContentStore,
  LocationStore: LocationStore,
  Router: Router,
  RouteTargetResolver: RouteTargetResolver,
  Target: Target,
  createRouter: createRouter
};
