// Generated by CoffeeScript 1.10.0
var areTargetsEqual, startsWith;

startsWith = function(str, prefix) {
  return str.substr(0, prefix.length) === prefix;
};

areTargetsEqual = function(a, b) {
  return a.targetPath === b.targetPath && JSON.stringify(a.params || {}) === JSON.stringify(b.params || {});
};

module.exports = {
  areTargetsEqual: areTargetsEqual,
  startsWith: startsWith
};
