// Generated by CoffeeScript 1.10.0
var areLocationsEqual, areTargetsEqual, startsWith;

startsWith = function(str, prefix) {
  return str.substr(0, prefix.length) === prefix;
};

areLocationsEqual = function(a, b) {
  if (a === b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return a.pathname === b.pathname;
};

areTargetsEqual = function(a, b) {
  if (a === b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return a.targetPath === b.targetPath && JSON.stringify(a.params || {}) === JSON.stringify(b.params || {});
};

module.exports = {
  areLocationsEqual: areLocationsEqual,
  areTargetsEqual: areTargetsEqual,
  startsWith: startsWith
};
