// Generated by CoffeeScript 1.10.0
var LocationContent, React,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

React = require('react');

LocationContent = (function(superClass) {
  extend(LocationContent, superClass);

  LocationContent.propTypes = {
    contentStore: React.PropTypes.object.isRequired
  };

  function LocationContent() {
    this._handleLocationChange = bind(this._handleLocationChange, this);
    LocationContent.__super__.constructor.apply(this, arguments);
    this.state = this._getContentStoreState();
  }

  LocationContent.prototype._getContentStoreState = function() {
    return {
      contentComponent: this.props.contentStore.getCurrentTargetElement()
    };
  };

  LocationContent.prototype.componentDidMount = function() {
    return this.props.contentStore.on('change', this._handleLocationChange);
  };

  LocationContent.prototype.componentWillUnmount = function() {
    return this.props.contentStore.removeListener('change', this._handleLocationChange);
  };

  LocationContent.prototype._handleLocationChange = function() {
    return this.setState(this._getContentStoreState());
  };

  LocationContent.prototype.render = function() {
    return this.state.contentComponent || React.createElement("div", null);
  };

  return LocationContent;

})(React.Component);

module.exports = LocationContent;
